/*
 * Bitmask and offset defintions for all the Hanadu Registers.
 * Processor Interface Version: 1
 * 
 * THIS FILE IS AUTOMATICALLY GENERATED USING THE REGISTER MAP PROJECT.
 * PLEASE DO NOT EDIT.
 *
 * Martin Townsend >martin.townsend@xsilon.com<
 * Copyright Xsilon Limited 2014.
 */

#ifndef _XSILON_REGMAP_AUTOGENERATED_QEMU_HANADU_DEVICE_H
#define _XSILON_REGMAP_AUTOGENERATED_QEMU_HANADU_DEVICE_H

#include <stdint.h>
#include "exec/hwaddr.h"

/* __________________________________________________ Register Access Prototypes
 */

void
han_trxm_reg_reset(void *opaque) __attribute__((weak));
uint64_t
han_trxm_mem_region_read(void *opaque, hwaddr addr, unsigned size) __attribute__((weak));
void
han_trxm_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size) __attribute__((weak));


void
han_mac_reg_reset(void *opaque) __attribute__((weak));
uint64_t
han_mac_mem_region_read(void *opaque, hwaddr addr, unsigned size) __attribute__((weak));
void
han_mac_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size) __attribute__((weak));


void
han_pwr_reg_reset(void *opaque) __attribute__((weak));
uint64_t
han_pwr_mem_region_read(void *opaque, hwaddr addr, unsigned size) __attribute__((weak));
void
han_pwr_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size) __attribute__((weak));


void
han_afe_reg_reset(void *opaque) __attribute__((weak));
uint64_t
han_afe_mem_region_read(void *opaque, hwaddr addr, unsigned size) __attribute__((weak));
void
han_afe_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size) __attribute__((weak));


void
han_hwvers_reg_reset(void *opaque) __attribute__((weak));
uint64_t
han_hwvers_mem_region_read(void *opaque, hwaddr addr, unsigned size) __attribute__((weak));
void
han_hwvers_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size) __attribute__((weak));



/* ____________________________________________ HW Block Register Map Structures
 */

typedef void (* field_changed_fn)(uint32_t value, void *hw_block);


/* ___________________ Transceiver
 */

typedef int (* reg_changed_fn)(uint32_t value);
typedef int (* reg_read_fn)(uint32_t *value, void *hw_block);

struct han_regmap_trxm
{
    /* 0  */ uint32_t trx_tx_ctrl;
    /* 1  */ uint32_t trx_tx_hwbuf0_rc_psdulen;
    /* 2  */ uint32_t trx_tx_hwbuf0_xtra;
    /* 3  */ uint32_t trx_tx_hwbuf1_rc_psdulen;
    /* 4  */ uint32_t trx_tx_hwbuf1_xtra;
    /* 5  */ uint32_t trx_rx_control;
    /* 6  */ uint32_t trx_rx_not_used1;
    /* 7  */ uint32_t trx_rx_hdr_rep_rate;
    /* 8  */ uint32_t trx_rx_thresholds;
    /* 9  */ uint32_t trx_rx_resets;
    /* 10 */ uint32_t trx_rx_next_membank_to_proc;
    /* 11 */ uint32_t trx_rx_hdr_crc_pass_count;
    /* 12 */ uint32_t trx_rx_hdr_crc_fail_count;
    /* 13 */ uint32_t trx_rx_pay_crc_pass_count;
    /* 14 */ uint32_t trx_rx_pay_crc_fail_count;
    /* 15 */ uint32_t trx_rx_buf0_rc_psdulen;
    /* 16 */ uint32_t trx_rx_buf0_xtra;
    /* 17 */ uint32_t trx_rx_rx_buf0_crc;
    /* 18 */ uint32_t trx_rx_buf1_rc_psdulen;
    /* 19 */ uint32_t trx_rx_buf1_xtra;
    /* 20 */ uint32_t trx_rx_rx_buf1_crc;
    /* 21 */ uint32_t trx_rx_buf2_rc_psdulen;
    /* 22 */ uint32_t trx_rx_buf2_xtra;
    /* 23 */ uint32_t trx_rx_rx_buf2_crc;
    /* 24 */ uint32_t trx_rx_buf3_rc_psdulen;
    /* 25 */ uint32_t trx_rx_buf3_xtra;
    /* 26 */ uint32_t trx_rx_rx_buf3_crc;
    /* 27 */ uint32_t trx_xcorr_thresh;
    /* 28 */ uint32_t trx_rx_fifo_levels;
    /* 29 */ uint32_t trx_hard_reset;
    /* 30 */ uint32_t trx_pga_gain_cca_flags;
    /* 31 */ uint32_t trx_membank_fifo_flags_rssi_tx_power;

    /* Reg changed callback, implement if required */
    struct reg_trxm_changed_fns {
        /* 0  */ reg_changed_fn trx_tx_ctrl_changed_cb;
        /* 1  */ reg_changed_fn trx_tx_hwbuf0_rc_psdulen_changed_cb;
        /* 2  */ reg_changed_fn trx_tx_hwbuf0_xtra_changed_cb;
        /* 3  */ reg_changed_fn trx_tx_hwbuf1_rc_psdulen_changed_cb;
        /* 4  */ reg_changed_fn trx_tx_hwbuf1_xtra_changed_cb;
        /* 5  */ reg_changed_fn trx_rx_control_changed_cb;
        /* 6  */ reg_changed_fn trx_rx_not_used1_changed_cb;
        /* 7  */ reg_changed_fn trx_rx_hdr_rep_rate_changed_cb;
        /* 8  */ reg_changed_fn trx_rx_thresholds_changed_cb;
        /* 9  */ reg_changed_fn trx_rx_resets_changed_cb;
        /* 10 */ reg_changed_fn trx_rx_next_membank_to_proc_changed_cb;
        /* 11 */ reg_changed_fn trx_rx_hdr_crc_pass_count_changed_cb;
        /* 12 */ reg_changed_fn trx_rx_hdr_crc_fail_count_changed_cb;
        /* 13 */ reg_changed_fn trx_rx_pay_crc_pass_count_changed_cb;
        /* 14 */ reg_changed_fn trx_rx_pay_crc_fail_count_changed_cb;
        /* 15 */ reg_changed_fn trx_rx_buf0_rc_psdulen_changed_cb;
        /* 16 */ reg_changed_fn trx_rx_buf0_xtra_changed_cb;
        /* 17 */ reg_changed_fn trx_rx_rx_buf0_crc_changed_cb;
        /* 18 */ reg_changed_fn trx_rx_buf1_rc_psdulen_changed_cb;
        /* 19 */ reg_changed_fn trx_rx_buf1_xtra_changed_cb;
        /* 20 */ reg_changed_fn trx_rx_rx_buf1_crc_changed_cb;
        /* 21 */ reg_changed_fn trx_rx_buf2_rc_psdulen_changed_cb;
        /* 22 */ reg_changed_fn trx_rx_buf2_xtra_changed_cb;
        /* 23 */ reg_changed_fn trx_rx_rx_buf2_crc_changed_cb;
        /* 24 */ reg_changed_fn trx_rx_buf3_rc_psdulen_changed_cb;
        /* 25 */ reg_changed_fn trx_rx_buf3_xtra_changed_cb;
        /* 26 */ reg_changed_fn trx_rx_rx_buf3_crc_changed_cb;
        /* 27 */ reg_changed_fn trx_xcorr_thresh_changed_cb;
        /* 28 */ reg_changed_fn trx_rx_fifo_levels_changed_cb;
        /* 29 */ reg_changed_fn trx_hard_reset_changed_cb;
        /* 30 */ reg_changed_fn trx_pga_gain_cca_flags_changed_cb;
        /* 31 */ reg_changed_fn trx_membank_fifo_flags_rssi_tx_power_changed_cb;
    } reg_changed;

    /* Reg field changed callback, implement if required */
    struct field_trxm_changed_fns {
        field_changed_fn tx_use_ram_changed;
        field_changed_fn tx_mem_bank_select_changed;
        field_changed_fn tx_start_changed;
        field_changed_fn tx_enable_changed;
        field_changed_fn tx_att_20db0_changed;
        field_changed_fn tx_att_10db0_changed;
        field_changed_fn tx_pga_gain0_changed;
        field_changed_fn tx_psdu_len0_changed;
        field_changed_fn tx_rep_code0_changed;
        field_changed_fn tx_hdr_preamble0_changed;
        field_changed_fn tx_hdr_extra0_changed;
        field_changed_fn tx_att_20db1_changed;
        field_changed_fn tx_att_10db1_changed;
        field_changed_fn tx_pga_gain1_changed;
        field_changed_fn tx_psdu_len1_changed;
        field_changed_fn tx_rep_code1_changed;
        field_changed_fn tx_preamble1_changed;
        field_changed_fn tx_hdr_extra1_changed;
        field_changed_fn rx_acg_max_db_changed;
        field_changed_fn rx_acg_lower_thresh_changed;
        field_changed_fn rx_acg_set_point_changed;
        field_changed_fn rx_manual_membank_sel_changed;
        field_changed_fn rx_payload_fail_crc_intr_en_changed;
        field_changed_fn rx_clear_membank_oflow_changed;
        field_changed_fn rx_clear_membank_full3_changed;
        field_changed_fn rx_clear_membank_full2_changed;
        field_changed_fn rx_clear_membank_full1_changed;
        field_changed_fn rx_clear_membank_full0_changed;
        field_changed_fn rx_enable_changed;
        field_changed_fn trx_num_carriers_changed;
        field_changed_fn rx_hdr_reprate_changed;
        field_changed_fn rx_hp_auto_threshold_changed;
        field_changed_fn rx_cca_auto_threshold_changed;
        field_changed_fn rx_ed_threshold_changed;
    } field_changed;

    /* Reg Read callback, implement if required */
    struct reg_trxm_read_fns {
        /* 0  */ reg_read_fn trx_tx_ctrl_read_cb;
        /* 1  */ reg_read_fn trx_tx_hwbuf0_rc_psdulen_read_cb;
        /* 2  */ reg_read_fn trx_tx_hwbuf0_xtra_read_cb;
        /* 3  */ reg_read_fn trx_tx_hwbuf1_rc_psdulen_read_cb;
        /* 4  */ reg_read_fn trx_tx_hwbuf1_xtra_read_cb;
        /* 5  */ reg_read_fn trx_rx_control_read_cb;
        /* 6  */ reg_read_fn trx_rx_not_used1_read_cb;
        /* 7  */ reg_read_fn trx_rx_hdr_rep_rate_read_cb;
        /* 8  */ reg_read_fn trx_rx_thresholds_read_cb;
        /* 9  */ reg_read_fn trx_rx_resets_read_cb;
        /* 10 */ reg_read_fn trx_rx_next_membank_to_proc_read_cb;
        /* 11 */ reg_read_fn trx_rx_hdr_crc_pass_count_read_cb;
        /* 12 */ reg_read_fn trx_rx_hdr_crc_fail_count_read_cb;
        /* 13 */ reg_read_fn trx_rx_pay_crc_pass_count_read_cb;
        /* 14 */ reg_read_fn trx_rx_pay_crc_fail_count_read_cb;
        /* 15 */ reg_read_fn trx_rx_buf0_rc_psdulen_read_cb;
        /* 16 */ reg_read_fn trx_rx_buf0_xtra_read_cb;
        /* 17 */ reg_read_fn trx_rx_rx_buf0_crc_read_cb;
        /* 18 */ reg_read_fn trx_rx_buf1_rc_psdulen_read_cb;
        /* 19 */ reg_read_fn trx_rx_buf1_xtra_read_cb;
        /* 20 */ reg_read_fn trx_rx_rx_buf1_crc_read_cb;
        /* 21 */ reg_read_fn trx_rx_buf2_rc_psdulen_read_cb;
        /* 22 */ reg_read_fn trx_rx_buf2_xtra_read_cb;
        /* 23 */ reg_read_fn trx_rx_rx_buf2_crc_read_cb;
        /* 24 */ reg_read_fn trx_rx_buf3_rc_psdulen_read_cb;
        /* 25 */ reg_read_fn trx_rx_buf3_xtra_read_cb;
        /* 26 */ reg_read_fn trx_rx_rx_buf3_crc_read_cb;
        /* 27 */ reg_read_fn trx_xcorr_thresh_read_cb;
        /* 28 */ reg_read_fn trx_rx_fifo_levels_read_cb;
        /* 29 */ reg_read_fn trx_hard_reset_read_cb;
        /* 30 */ reg_read_fn trx_pga_gain_cca_flags_read_cb;
        /* 31 */ reg_read_fn trx_membank_fifo_flags_rssi_tx_power_read_cb;
    } reg_read;
};

/* ___________________ Medium Access Controller
 */

typedef int (* reg_changed_fn)(uint32_t value);
typedef int (* reg_read_fn)(uint32_t *value, void *hw_block);

struct han_regmap_mac
{
    /* 0  */ uint32_t mac_traf_mon_ctrl;
    /* 1  */ uint32_t mac_traf_mon_clear;
    /* 2  */ uint32_t mac_ifs;
    /* 3  */ uint32_t dummy3;
    /* 4  */ uint32_t dummy4;
    /* 5  */ uint32_t dummy5;
    /* 6  */ uint32_t dummy6;
    /* 7  */ uint32_t dummy7;
    /* 8  */ uint32_t dummy8;
    /* 9  */ uint32_t dummy9;
    /* 10 */ uint32_t mac_traf_mon_psdu_avg;
    /* 11 */ uint32_t mac_traf_mon_repcode_avg;
    /* 12 */ uint32_t mac_traf_mon_hdr_crc_pass;
    /* 13 */ uint32_t mac_traf_mon_hdr_crc_fail;
    /* 14 */ uint32_t mac_traf_mon_payload_crc_fail;
    /* 15 */ uint32_t mac_traf_mon_cca;
    /* 16 */ uint32_t mac_traf_mon_pkt_time;
    /* 17 */ uint32_t mac_traf_mon_hp;
    /* 18 */ uint32_t mac_filter_ea_lower;
    /* 19 */ uint32_t mac_filter_ea_upper;
    /* 20 */ uint32_t mac_filter_sa;
    /* 21 */ uint32_t mac_filter_pan_id;
    /* 22 */ uint32_t mac_filter_ctrl;
    /* 23 */ uint32_t mac_lower_ctrl;
    /* 24 */ uint32_t mac_lower_status;
    /* 25 */ uint32_t mac_ack_control;
    /* 26 */ uint32_t mac_ack_payload;
    /* 27 */ uint32_t mac_ack_processing_ctrl;
    /* 28 */ uint32_t mac_ack_processing_status;
    /* 29 */ uint32_t mac_ack_data;
    /* 30 */ uint32_t dummy30;
    /* 31 */ uint32_t dummy31;

    /* Reg changed callback, implement if required */
    struct reg_mac_changed_fns {
        /* 0  */ reg_changed_fn mac_traf_mon_ctrl_changed_cb;
        /* 1  */ reg_changed_fn mac_traf_mon_clear_changed_cb;
        /* 2  */ reg_changed_fn mac_ifs_changed_cb;
        /* 3  */ reg_changed_fn dummy3_cb;
        /* 4  */ reg_changed_fn dummy4_cb;
        /* 5  */ reg_changed_fn dummy5_cb;
        /* 6  */ reg_changed_fn dummy6_cb;
        /* 7  */ reg_changed_fn dummy7_cb;
        /* 8  */ reg_changed_fn dummy8_cb;
        /* 9  */ reg_changed_fn dummy9_cb;
        /* 10 */ reg_changed_fn mac_traf_mon_psdu_avg_changed_cb;
        /* 11 */ reg_changed_fn mac_traf_mon_repcode_avg_changed_cb;
        /* 12 */ reg_changed_fn mac_traf_mon_hdr_crc_pass_changed_cb;
        /* 13 */ reg_changed_fn mac_traf_mon_hdr_crc_fail_changed_cb;
        /* 14 */ reg_changed_fn mac_traf_mon_payload_crc_fail_changed_cb;
        /* 15 */ reg_changed_fn mac_traf_mon_cca_changed_cb;
        /* 16 */ reg_changed_fn mac_traf_mon_pkt_time_changed_cb;
        /* 17 */ reg_changed_fn mac_traf_mon_hp_changed_cb;
        /* 18 */ reg_changed_fn mac_filter_ea_lower_changed_cb;
        /* 19 */ reg_changed_fn mac_filter_ea_upper_changed_cb;
        /* 20 */ reg_changed_fn mac_filter_sa_changed_cb;
        /* 21 */ reg_changed_fn mac_filter_pan_id_changed_cb;
        /* 22 */ reg_changed_fn mac_filter_ctrl_changed_cb;
        /* 23 */ reg_changed_fn mac_lower_ctrl_changed_cb;
        /* 24 */ reg_changed_fn mac_lower_status_changed_cb;
        /* 25 */ reg_changed_fn mac_ack_control_changed_cb;
        /* 26 */ reg_changed_fn mac_ack_payload_changed_cb;
        /* 27 */ reg_changed_fn mac_ack_processing_ctrl_changed_cb;
        /* 28 */ reg_changed_fn mac_ack_processing_status_changed_cb;
        /* 29 */ reg_changed_fn mac_ack_data_changed_cb;
        /* 30 */ reg_changed_fn dummy30_cb;
        /* 31 */ reg_changed_fn dummy31_cb;
    } reg_changed;

    /* Reg field changed callback, implement if required */
    struct field_mac_changed_fns {
        field_changed_fn lifs_period_changed;
        field_changed_fn sifs_period_changed;
        field_changed_fn max_sifs_frame_size_changed;
        field_changed_fn ifs_enable_changed;
        field_changed_fn ctrl_pan_coord_changed;
        field_changed_fn ctrl_filter_enable_changed;
        field_changed_fn timeout_strategy_changed;
        field_changed_fn max_csma_backoffs_changed;
        field_changed_fn min_be_changed;
        field_changed_fn max_be_changed;
        field_changed_fn csma_ign_rx_busy_changed;
        field_changed_fn lower_ack_override_changed;
        field_changed_fn lower_reset_changed;
        field_changed_fn lower_mac_bypass_changed;
        field_changed_fn ack_pga_gain_changed;
        field_changed_fn ack_rep_code_changed;
        field_changed_fn ack_seq_check_changed;
        field_changed_fn ack_destination_changed;
        field_changed_fn ack_enable_changed;
        field_changed_fn ack_extra_hdr_changed;
        field_changed_fn ack_fc1_changed;
        field_changed_fn ack_fc0_changed;
        field_changed_fn max_retries_changed;
        field_changed_fn ack_wait_dur_changed;
    } field_changed;

    /* Reg Read callback, implement if required */
    struct reg_mac_read_fns {
        /* 0  */ reg_read_fn mac_traf_mon_ctrl_read_cb;
        /* 1  */ reg_read_fn mac_traf_mon_clear_read_cb;
        /* 2  */ reg_read_fn mac_ifs_read_cb;
        /* 3  */ reg_read_fn dummy3_cb;
        /* 4  */ reg_read_fn dummy4_cb;
        /* 5  */ reg_read_fn dummy5_cb;
        /* 6  */ reg_read_fn dummy6_cb;
        /* 7  */ reg_read_fn dummy7_cb;
        /* 8  */ reg_read_fn dummy8_cb;
        /* 9  */ reg_read_fn dummy9_cb;
        /* 10 */ reg_read_fn mac_traf_mon_psdu_avg_read_cb;
        /* 11 */ reg_read_fn mac_traf_mon_repcode_avg_read_cb;
        /* 12 */ reg_read_fn mac_traf_mon_hdr_crc_pass_read_cb;
        /* 13 */ reg_read_fn mac_traf_mon_hdr_crc_fail_read_cb;
        /* 14 */ reg_read_fn mac_traf_mon_payload_crc_fail_read_cb;
        /* 15 */ reg_read_fn mac_traf_mon_cca_read_cb;
        /* 16 */ reg_read_fn mac_traf_mon_pkt_time_read_cb;
        /* 17 */ reg_read_fn mac_traf_mon_hp_read_cb;
        /* 18 */ reg_read_fn mac_filter_ea_lower_read_cb;
        /* 19 */ reg_read_fn mac_filter_ea_upper_read_cb;
        /* 20 */ reg_read_fn mac_filter_sa_read_cb;
        /* 21 */ reg_read_fn mac_filter_pan_id_read_cb;
        /* 22 */ reg_read_fn mac_filter_ctrl_read_cb;
        /* 23 */ reg_read_fn mac_lower_ctrl_read_cb;
        /* 24 */ reg_read_fn mac_lower_status_read_cb;
        /* 25 */ reg_read_fn mac_ack_control_read_cb;
        /* 26 */ reg_read_fn mac_ack_payload_read_cb;
        /* 27 */ reg_read_fn mac_ack_processing_ctrl_read_cb;
        /* 28 */ reg_read_fn mac_ack_processing_status_read_cb;
        /* 29 */ reg_read_fn mac_ack_data_read_cb;
        /* 30 */ reg_read_fn dummy30_cb;
        /* 31 */ reg_read_fn dummy31_cb;
    } reg_read;
};

/* ___________________ Power Up Controller
 */

typedef int (* reg_changed_fn)(uint32_t value);
typedef int (* reg_read_fn)(uint32_t *value, void *hw_block);

struct han_regmap_pwr
{
    /* 0  */ uint32_t dummy0;
    /* 1  */ uint32_t pup_kick_off_sw_ad9865_spi_write;
    /* 2  */ uint32_t pup_kick_off_sw_ad9865_spi_read;
    /* 3  */ uint32_t pup_tx_rx_select;
    /* 4  */ uint32_t pup_pga_mux_select;
    /* 5  */ uint32_t pup_tx_tongen_mux_select;
    /* 6  */ uint32_t pup_afe_reset;
    /* 7  */ uint32_t pup_dcm_reset;
    /* 8  */ uint32_t dummy8;
    /* 9  */ uint32_t pup_appliance_on;
    /* 10 */ uint32_t pup_fpga_config;
    /* 11 */ uint32_t dummy11;
    /* 12 */ uint32_t dummy12;
    /* 13 */ uint32_t dummy13;
    /* 14 */ uint32_t pup_leds;
    /* 15 */ uint32_t dummy15;
    /* 16 */ uint32_t dummy16;
    /* 17 */ uint32_t dummy17;
    /* 18 */ uint32_t pup_dips1;
    /* 19 */ uint32_t pup_dips2;
    /* 20 */ uint32_t dummy20;
    /* 21 */ uint32_t dummy21;
    /* 22 */ uint32_t dummy22;
    /* 23 */ uint32_t dummy23;
    /* 24 */ uint32_t dummy24;
    /* 25 */ uint32_t dummy25;
    /* 26 */ uint32_t dummy26;
    /* 27 */ uint32_t dummy27;
    /* 28 */ uint32_t dummy28;
    /* 29 */ uint32_t dummy29;
    /* 30 */ uint32_t dummy30;
    /* 31 */ uint32_t dummy31;

    /* Reg changed callback, implement if required */
    struct reg_pwr_changed_fns {
        /* 0  */ reg_changed_fn dummy0_cb;
        /* 1  */ reg_changed_fn pup_kick_off_sw_ad9865_spi_write_changed_cb;
        /* 2  */ reg_changed_fn pup_kick_off_sw_ad9865_spi_read_changed_cb;
        /* 3  */ reg_changed_fn pup_tx_rx_select_changed_cb;
        /* 4  */ reg_changed_fn pup_pga_mux_select_changed_cb;
        /* 5  */ reg_changed_fn pup_tx_tongen_mux_select_changed_cb;
        /* 6  */ reg_changed_fn pup_afe_reset_changed_cb;
        /* 7  */ reg_changed_fn pup_dcm_reset_changed_cb;
        /* 8  */ reg_changed_fn dummy8_cb;
        /* 9  */ reg_changed_fn pup_appliance_on_changed_cb;
        /* 10 */ reg_changed_fn pup_fpga_config_changed_cb;
        /* 11 */ reg_changed_fn dummy11_cb;
        /* 12 */ reg_changed_fn dummy12_cb;
        /* 13 */ reg_changed_fn dummy13_cb;
        /* 14 */ reg_changed_fn pup_leds_changed_cb;
        /* 15 */ reg_changed_fn dummy15_cb;
        /* 16 */ reg_changed_fn dummy16_cb;
        /* 17 */ reg_changed_fn dummy17_cb;
        /* 18 */ reg_changed_fn pup_dips1_changed_cb;
        /* 19 */ reg_changed_fn pup_dips2_changed_cb;
        /* 20 */ reg_changed_fn dummy20_cb;
        /* 21 */ reg_changed_fn dummy21_cb;
        /* 22 */ reg_changed_fn dummy22_cb;
        /* 23 */ reg_changed_fn dummy23_cb;
        /* 24 */ reg_changed_fn dummy24_cb;
        /* 25 */ reg_changed_fn dummy25_cb;
        /* 26 */ reg_changed_fn dummy26_cb;
        /* 27 */ reg_changed_fn dummy27_cb;
        /* 28 */ reg_changed_fn dummy28_cb;
        /* 29 */ reg_changed_fn dummy29_cb;
        /* 30 */ reg_changed_fn dummy30_cb;
        /* 31 */ reg_changed_fn dummy31_cb;
    } reg_changed;

    /* Reg field changed callback, implement if required */
    struct field_pwr_changed_fns {
        field_changed_fn pup_kick_off_spi_write_changed;
        field_changed_fn pup_kick_off_spi_read_changed;
        field_changed_fn relay_changed;
        field_changed_fn fpga_config_changed;
    } field_changed;

    /* Reg Read callback, implement if required */
    struct reg_pwr_read_fns {
        /* 0  */ reg_read_fn dummy0_cb;
        /* 1  */ reg_read_fn pup_kick_off_sw_ad9865_spi_write_read_cb;
        /* 2  */ reg_read_fn pup_kick_off_sw_ad9865_spi_read_read_cb;
        /* 3  */ reg_read_fn pup_tx_rx_select_read_cb;
        /* 4  */ reg_read_fn pup_pga_mux_select_read_cb;
        /* 5  */ reg_read_fn pup_tx_tongen_mux_select_read_cb;
        /* 6  */ reg_read_fn pup_afe_reset_read_cb;
        /* 7  */ reg_read_fn pup_dcm_reset_read_cb;
        /* 8  */ reg_read_fn dummy8_cb;
        /* 9  */ reg_read_fn pup_appliance_on_read_cb;
        /* 10 */ reg_read_fn pup_fpga_config_read_cb;
        /* 11 */ reg_read_fn dummy11_cb;
        /* 12 */ reg_read_fn dummy12_cb;
        /* 13 */ reg_read_fn dummy13_cb;
        /* 14 */ reg_read_fn pup_leds_read_cb;
        /* 15 */ reg_read_fn dummy15_cb;
        /* 16 */ reg_read_fn dummy16_cb;
        /* 17 */ reg_read_fn dummy17_cb;
        /* 18 */ reg_read_fn pup_dips1_read_cb;
        /* 19 */ reg_read_fn pup_dips2_read_cb;
        /* 20 */ reg_read_fn dummy20_cb;
        /* 21 */ reg_read_fn dummy21_cb;
        /* 22 */ reg_read_fn dummy22_cb;
        /* 23 */ reg_read_fn dummy23_cb;
        /* 24 */ reg_read_fn dummy24_cb;
        /* 25 */ reg_read_fn dummy25_cb;
        /* 26 */ reg_read_fn dummy26_cb;
        /* 27 */ reg_read_fn dummy27_cb;
        /* 28 */ reg_read_fn dummy28_cb;
        /* 29 */ reg_read_fn dummy29_cb;
        /* 30 */ reg_read_fn dummy30_cb;
        /* 31 */ reg_read_fn dummy31_cb;
    } reg_read;
};

/* ___________________ AFE Controller
 */

typedef int (* reg_changed_fn)(uint32_t value);
typedef int (* reg_read_fn)(uint32_t *value, void *hw_block);

struct han_regmap_afe
{
    /* 0  */ uint32_t afe_agc_fixed_gain;
    /* 1  */ uint32_t afe_status;
    /* 2  */ uint32_t afe_ad9865_write_reg_0_3;
    /* 3  */ uint32_t afe_ad9865_write_reg_4_7;
    /* 4  */ uint32_t afe_ad9865_write_reg_8_11;
    /* 5  */ uint32_t afe_ad9865_write_reg_12_15;
    /* 6  */ uint32_t afe_ad9865_write_reg_16_19;
    /* 7  */ uint32_t afe_ad9865_read_reg_0_3;
    /* 8  */ uint32_t afe_ad9865_read_reg_4_7;
    /* 9  */ uint32_t afe_ad9865_read_reg_8_11;
    /* 10 */ uint32_t afe_ad9865_read_reg_12_15;
    /* 11 */ uint32_t afe_ad9865_read_reg_16_19;
    /* 12 */ uint32_t dummy12;
    /* 13 */ uint32_t dummy13;
    /* 14 */ uint32_t dummy14;
    /* 15 */ uint32_t dummy15;
    /* 16 */ uint32_t dummy16;
    /* 17 */ uint32_t dummy17;
    /* 18 */ uint32_t dummy18;
    /* 19 */ uint32_t dummy19;
    /* 20 */ uint32_t dummy20;
    /* 21 */ uint32_t dummy21;
    /* 22 */ uint32_t dummy22;
    /* 23 */ uint32_t dummy23;
    /* 24 */ uint32_t dummy24;
    /* 25 */ uint32_t dummy25;
    /* 26 */ uint32_t dummy26;
    /* 27 */ uint32_t dummy27;
    /* 28 */ uint32_t dummy28;
    /* 29 */ uint32_t dummy29;
    /* 30 */ uint32_t dummy30;
    /* 31 */ uint32_t dummy31;

    /* Reg changed callback, implement if required */
    struct reg_afe_changed_fns {
        /* 0  */ reg_changed_fn afe_agc_fixed_gain_changed_cb;
        /* 1  */ reg_changed_fn afe_status_changed_cb;
        /* 2  */ reg_changed_fn afe_ad9865_write_reg_0_3_changed_cb;
        /* 3  */ reg_changed_fn afe_ad9865_write_reg_4_7_changed_cb;
        /* 4  */ reg_changed_fn afe_ad9865_write_reg_8_11_changed_cb;
        /* 5  */ reg_changed_fn afe_ad9865_write_reg_12_15_changed_cb;
        /* 6  */ reg_changed_fn afe_ad9865_write_reg_16_19_changed_cb;
        /* 7  */ reg_changed_fn afe_ad9865_read_reg_0_3_changed_cb;
        /* 8  */ reg_changed_fn afe_ad9865_read_reg_4_7_changed_cb;
        /* 9  */ reg_changed_fn afe_ad9865_read_reg_8_11_changed_cb;
        /* 10 */ reg_changed_fn afe_ad9865_read_reg_12_15_changed_cb;
        /* 11 */ reg_changed_fn afe_ad9865_read_reg_16_19_changed_cb;
        /* 12 */ reg_changed_fn dummy12_cb;
        /* 13 */ reg_changed_fn dummy13_cb;
        /* 14 */ reg_changed_fn dummy14_cb;
        /* 15 */ reg_changed_fn dummy15_cb;
        /* 16 */ reg_changed_fn dummy16_cb;
        /* 17 */ reg_changed_fn dummy17_cb;
        /* 18 */ reg_changed_fn dummy18_cb;
        /* 19 */ reg_changed_fn dummy19_cb;
        /* 20 */ reg_changed_fn dummy20_cb;
        /* 21 */ reg_changed_fn dummy21_cb;
        /* 22 */ reg_changed_fn dummy22_cb;
        /* 23 */ reg_changed_fn dummy23_cb;
        /* 24 */ reg_changed_fn dummy24_cb;
        /* 25 */ reg_changed_fn dummy25_cb;
        /* 26 */ reg_changed_fn dummy26_cb;
        /* 27 */ reg_changed_fn dummy27_cb;
        /* 28 */ reg_changed_fn dummy28_cb;
        /* 29 */ reg_changed_fn dummy29_cb;
        /* 30 */ reg_changed_fn dummy30_cb;
        /* 31 */ reg_changed_fn dummy31_cb;
    } reg_changed;

    /* Reg field changed callback, implement if required */
    struct field_afe_changed_fns {
        field_changed_fn afe_ad9865_spi_read_done_changed;
        field_changed_fn afe_ad9865_spi_write_done_changed;
    } field_changed;

    /* Reg Read callback, implement if required */
    struct reg_afe_read_fns {
        /* 0  */ reg_read_fn afe_agc_fixed_gain_read_cb;
        /* 1  */ reg_read_fn afe_status_read_cb;
        /* 2  */ reg_read_fn afe_ad9865_write_reg_0_3_read_cb;
        /* 3  */ reg_read_fn afe_ad9865_write_reg_4_7_read_cb;
        /* 4  */ reg_read_fn afe_ad9865_write_reg_8_11_read_cb;
        /* 5  */ reg_read_fn afe_ad9865_write_reg_12_15_read_cb;
        /* 6  */ reg_read_fn afe_ad9865_write_reg_16_19_read_cb;
        /* 7  */ reg_read_fn afe_ad9865_read_reg_0_3_read_cb;
        /* 8  */ reg_read_fn afe_ad9865_read_reg_4_7_read_cb;
        /* 9  */ reg_read_fn afe_ad9865_read_reg_8_11_read_cb;
        /* 10 */ reg_read_fn afe_ad9865_read_reg_12_15_read_cb;
        /* 11 */ reg_read_fn afe_ad9865_read_reg_16_19_read_cb;
        /* 12 */ reg_read_fn dummy12_cb;
        /* 13 */ reg_read_fn dummy13_cb;
        /* 14 */ reg_read_fn dummy14_cb;
        /* 15 */ reg_read_fn dummy15_cb;
        /* 16 */ reg_read_fn dummy16_cb;
        /* 17 */ reg_read_fn dummy17_cb;
        /* 18 */ reg_read_fn dummy18_cb;
        /* 19 */ reg_read_fn dummy19_cb;
        /* 20 */ reg_read_fn dummy20_cb;
        /* 21 */ reg_read_fn dummy21_cb;
        /* 22 */ reg_read_fn dummy22_cb;
        /* 23 */ reg_read_fn dummy23_cb;
        /* 24 */ reg_read_fn dummy24_cb;
        /* 25 */ reg_read_fn dummy25_cb;
        /* 26 */ reg_read_fn dummy26_cb;
        /* 27 */ reg_read_fn dummy27_cb;
        /* 28 */ reg_read_fn dummy28_cb;
        /* 29 */ reg_read_fn dummy29_cb;
        /* 30 */ reg_read_fn dummy30_cb;
        /* 31 */ reg_read_fn dummy31_cb;
    } reg_read;
};

/* ___________________ Hardware Version Control
 */

typedef int (* reg_changed_fn)(uint32_t value);
typedef int (* reg_read_fn)(uint32_t *value, void *hw_block);

struct han_regmap_hwvers
{
    /* 0  */ uint32_t major_ver;
    /* 1  */ uint32_t minor_ver;
    /* 2  */ uint32_t provisional_ver;
    /* 3  */ uint32_t proc_interface_ver;
    /* 4  */ uint32_t db_ver;
    /* 5  */ uint32_t dummy5;
    /* 6  */ uint32_t dummy6;
    /* 7  */ uint32_t dummy7;
    /* 8  */ uint32_t dummy8;
    /* 9  */ uint32_t dummy9;
    /* 10 */ uint32_t dummy10;
    /* 11 */ uint32_t dummy11;
    /* 12 */ uint32_t dummy12;
    /* 13 */ uint32_t dummy13;
    /* 14 */ uint32_t dummy14;
    /* 15 */ uint32_t dummy15;
    /* 16 */ uint32_t dummy16;
    /* 17 */ uint32_t dummy17;
    /* 18 */ uint32_t dummy18;
    /* 19 */ uint32_t dummy19;
    /* 20 */ uint32_t dummy20;
    /* 21 */ uint32_t dummy21;
    /* 22 */ uint32_t dummy22;
    /* 23 */ uint32_t dummy23;
    /* 24 */ uint32_t dummy24;
    /* 25 */ uint32_t dummy25;
    /* 26 */ uint32_t dummy26;
    /* 27 */ uint32_t dummy27;
    /* 28 */ uint32_t dummy28;
    /* 29 */ uint32_t dummy29;
    /* 30 */ uint32_t dummy30;
    /* 31 */ uint32_t dummy31;

    /* Reg changed callback, implement if required */
    struct reg_hwvers_changed_fns {
        /* 0  */ reg_changed_fn major_ver_changed_cb;
        /* 1  */ reg_changed_fn minor_ver_changed_cb;
        /* 2  */ reg_changed_fn provisional_ver_changed_cb;
        /* 3  */ reg_changed_fn proc_interface_ver_changed_cb;
        /* 4  */ reg_changed_fn db_ver_changed_cb;
        /* 5  */ reg_changed_fn dummy5_cb;
        /* 6  */ reg_changed_fn dummy6_cb;
        /* 7  */ reg_changed_fn dummy7_cb;
        /* 8  */ reg_changed_fn dummy8_cb;
        /* 9  */ reg_changed_fn dummy9_cb;
        /* 10 */ reg_changed_fn dummy10_cb;
        /* 11 */ reg_changed_fn dummy11_cb;
        /* 12 */ reg_changed_fn dummy12_cb;
        /* 13 */ reg_changed_fn dummy13_cb;
        /* 14 */ reg_changed_fn dummy14_cb;
        /* 15 */ reg_changed_fn dummy15_cb;
        /* 16 */ reg_changed_fn dummy16_cb;
        /* 17 */ reg_changed_fn dummy17_cb;
        /* 18 */ reg_changed_fn dummy18_cb;
        /* 19 */ reg_changed_fn dummy19_cb;
        /* 20 */ reg_changed_fn dummy20_cb;
        /* 21 */ reg_changed_fn dummy21_cb;
        /* 22 */ reg_changed_fn dummy22_cb;
        /* 23 */ reg_changed_fn dummy23_cb;
        /* 24 */ reg_changed_fn dummy24_cb;
        /* 25 */ reg_changed_fn dummy25_cb;
        /* 26 */ reg_changed_fn dummy26_cb;
        /* 27 */ reg_changed_fn dummy27_cb;
        /* 28 */ reg_changed_fn dummy28_cb;
        /* 29 */ reg_changed_fn dummy29_cb;
        /* 30 */ reg_changed_fn dummy30_cb;
        /* 31 */ reg_changed_fn dummy31_cb;
    } reg_changed;

    /* Reg field changed callback, implement if required */
    struct field_hwvers_changed_fns {
    } field_changed;

    /* Reg Read callback, implement if required */
    struct reg_hwvers_read_fns {
        /* 0  */ reg_read_fn major_ver_read_cb;
        /* 1  */ reg_read_fn minor_ver_read_cb;
        /* 2  */ reg_read_fn provisional_ver_read_cb;
        /* 3  */ reg_read_fn proc_interface_ver_read_cb;
        /* 4  */ reg_read_fn db_ver_read_cb;
        /* 5  */ reg_read_fn dummy5_cb;
        /* 6  */ reg_read_fn dummy6_cb;
        /* 7  */ reg_read_fn dummy7_cb;
        /* 8  */ reg_read_fn dummy8_cb;
        /* 9  */ reg_read_fn dummy9_cb;
        /* 10 */ reg_read_fn dummy10_cb;
        /* 11 */ reg_read_fn dummy11_cb;
        /* 12 */ reg_read_fn dummy12_cb;
        /* 13 */ reg_read_fn dummy13_cb;
        /* 14 */ reg_read_fn dummy14_cb;
        /* 15 */ reg_read_fn dummy15_cb;
        /* 16 */ reg_read_fn dummy16_cb;
        /* 17 */ reg_read_fn dummy17_cb;
        /* 18 */ reg_read_fn dummy18_cb;
        /* 19 */ reg_read_fn dummy19_cb;
        /* 20 */ reg_read_fn dummy20_cb;
        /* 21 */ reg_read_fn dummy21_cb;
        /* 22 */ reg_read_fn dummy22_cb;
        /* 23 */ reg_read_fn dummy23_cb;
        /* 24 */ reg_read_fn dummy24_cb;
        /* 25 */ reg_read_fn dummy25_cb;
        /* 26 */ reg_read_fn dummy26_cb;
        /* 27 */ reg_read_fn dummy27_cb;
        /* 28 */ reg_read_fn dummy28_cb;
        /* 29 */ reg_read_fn dummy29_cb;
        /* 30 */ reg_read_fn dummy30_cb;
        /* 31 */ reg_read_fn dummy31_cb;
    } reg_read;
};


/* ____________________________________________________________________ Bitmasks
 */

/* ___________________ Transceiver
 */
#define MAC_TX_ACK_BUSY_MASK                                        (0x00000020)
#define MAC_TX_ACK_BUSY_SHIFT                                       (5)
#define TX_BUSY_MASK                                                (0x00000010)
#define TX_BUSY_SHIFT                                               (4)
#define USER_TX_RAM_MASK                                            (0x00000008)
#define USER_TX_RAM_SHIFT                                           (3)
#define TX_MEMBANK_SEL_MASK                                         (0x00000004)
#define TX_MEMBANK_SEL_SHIFT                                        (2)
#define TX_START_MASK                                               (0x00000002)
#define TX_START_SHIFT                                              (1)
#define TX_ENABLE_MASK                                              (0x00000001)
#define TX_ENABLE_SHIFT                                             (0)
#define TX_ATT_20DB_MASK                                            (0x80000000)
#define TX_ATT_20DB_SHIFT                                           (31)
#define TX_ATT_10DB_MASK                                            (0x40000000)
#define TX_ATT_10DB_SHIFT                                           (30)
#define TX_PGA_GAIN_MASK                                            (0x3F000000)
#define TX_PGA_GAIN_SHIFT                                           (24)
#define TX_PSDU_LENGTH_MASK                                         (0x0003FF00)
#define TX_PSDU_LENGTH_SHIFT                                        (8)
#define TX_REP_CODE_MASK                                            (0x000000FF)
#define TX_REP_CODE_SHIFT                                           (0)
#define TX_PREAMBLE_MASK                                            (0x00070000)
#define TX_PREAMBLE_SHIFT                                           (16)
#define TX_HDR_XTRA_MASK                                            (0x0000FFFF)
#define TX_HDR_XTRA_SHIFT                                           (0)
#define TX_ATT_20DB_MASK                                            (0x80000000)
#define TX_ATT_20DB_SHIFT                                           (31)
#define TX_ATT_10DB_MASK                                            (0x40000000)
#define TX_ATT_10DB_SHIFT                                           (30)
#define TX_PGA_GAIN_MASK                                            (0x3F000000)
#define TX_PGA_GAIN_SHIFT                                           (24)
#define AGC_MAXDB_MASK                                              (0xFF000000)
#define AGC_MAXDB_SHIFT                                             (24)
#define AGC_LOWERTHRESH_MASK                                        (0x00FF0000)
#define AGC_LOWERTHRESH_SHIFT                                       (16)
#define AGC_SETPOINT_MASK                                           (0x0000FF00)
#define AGC_SETPOINT_SHIFT                                          (8)
#define AGC_MANUAL_MEMSEL_MASK                                      (0x00000080)
#define AGC_MANUAL_MEMSEL_SHIFT                                     (7)
#define PAYLOAD_CRCFAIL_INTR_MASK                                   (0x00000040)
#define PAYLOAD_CRCFAIL_INTR_SHIFT                                  (6)
#define CLEAR_MEMBANK_OFLOW_MASK                                    (0x00000020)
#define CLEAR_MEMBANK_OFLOW_SHIFT                                   (5)
#define CLEAR_MEM_FULL_FLAG_BANK3_MASK                              (0x00000010)
#define CLEAR_MEM_FULL_FLAG_BANK3_SHIFT                             (4)
#define CLEAR_MEM_FULL_FLAG_BANK2_MASK                              (0x00000008)
#define CLEAR_MEM_FULL_FLAG_BANK2_SHIFT                             (3)
#define CLEAR_MEM_FULL_FLAG_BANK1_MASK                              (0x00000004)
#define CLEAR_MEM_FULL_FLAG_BANK1_SHIFT                             (2)
#define CLEAR_MEM_FULL_FLAG_BANK0_MASK                              (0x00000002)
#define CLEAR_MEM_FULL_FLAG_BANK0_SHIFT                             (1)
#define RXM_ENABLE_MASK                                             (0x00000001)
#define RXM_ENABLE_SHIFT                                            (0)
#define NUM_CARRIERS_MASK                                           (0x00007F00)
#define NUM_CARRIERS_SHIFT                                          (8)
#define HDR_REPRATE_MASK                                            (0x000000FF)
#define HDR_REPRATE_SHIFT                                           (0)
#define HP_THRESHOLD_MASK                                           (0x00FF0000)
#define HP_THRESHOLD_SHIFT                                          (16)
#define CCA_THRESHOLD_MASK                                          (0x0000FF00)
#define CCA_THRESHOLD_SHIFT                                         (8)
#define ED_THRESHOLD_MASK                                           (0x000000FF)
#define ED_THRESHOLD_SHIFT                                          (0)
#define RESET_PREAMBLE_SIG3_MASK                                    (0x08000000)
#define RESET_PREAMBLE_SIG3_SHIFT                                   (27)
#define RESET_PREAMBLE_SIG2_MASK                                    (0x04000000)
#define RESET_PREAMBLE_SIG2_SHIFT                                   (26)
#define RESET_PREAMBLE_SIG1_MASK                                    (0x02000000)
#define RESET_PREAMBLE_SIG1_SHIFT                                   (25)
#define RESET_PREAMBLE_SIG0_MASK                                    (0x01000000)
#define RESET_PREAMBLE_SIG0_SHIFT                                   (24)
#define RESET_EXTRA_HDR3_MASK                                       (0x00800000)
#define RESET_EXTRA_HDR3_SHIFT                                      (23)
#define RESET_EXTRA_HDR2_MASK                                       (0x00400000)
#define RESET_EXTRA_HDR2_SHIFT                                      (22)
#define RESET_EXTRA_HDR1_MASK                                       (0x00200000)
#define RESET_EXTRA_HDR1_SHIFT                                      (21)
#define RESET_EXTRA_HDR0_MASK                                       (0x00100000)
#define RESET_EXTRA_HDR0_SHIFT                                      (20)
#define RESET_PAYLOAD_CRC3_MASK                                     (0x00080000)
#define RESET_PAYLOAD_CRC3_SHIFT                                    (19)
#define RESET_HEADER_CRC3_MASK                                      (0x00040000)
#define RESET_HEADER_CRC3_SHIFT                                     (18)
#define RESET_PSDU_LEN3_MASK                                        (0x00020000)
#define RESET_PSDU_LEN3_SHIFT                                       (17)
#define RESET_REPCODE3_MASK                                         (0x00010000)
#define RESET_REPCODE3_SHIFT                                        (16)
#define RESET_PAYLOAD_CRC2_MASK                                     (0x00008000)
#define RESET_PAYLOAD_CRC2_SHIFT                                    (15)
#define RESET_HEADER_CRC2_MASK                                      (0x00004000)
#define RESET_HEADER_CRC2_SHIFT                                     (14)
#define RESET_PSDU_LEN2_MASK                                        (0x00002000)
#define RESET_PSDU_LEN2_SHIFT                                       (13)
#define RESET_REPCODE2_MASK                                         (0x00001000)
#define RESET_REPCODE2_SHIFT                                        (12)
#define RESET_PAYLOAD_CRC1_MASK                                     (0x00000800)
#define RESET_PAYLOAD_CRC1_SHIFT                                    (11)
#define RESET_HEADER_CRC1_MASK                                      (0x00000400)
#define RESET_HEADER_CRC1_SHIFT                                     (10)
#define RESET_PSDU_LEN1_MASK                                        (0x00000200)
#define RESET_PSDU_LEN1_SHIFT                                       (9)
#define RESET_REPCODE1_MASK                                         (0x00000100)
#define RESET_REPCODE1_SHIFT                                        (8)
#define RESET_PAYLOAD_CRC0_MASK                                     (0x00000080)
#define RESET_PAYLOAD_CRC0_SHIFT                                    (7)
#define RESET_HEADER_CRC0_MASK                                      (0x00000040)
#define RESET_HEADER_CRC0_SHIFT                                     (6)
#define RESET_PSDU_LEN0_MASK                                        (0x00000020)
#define RESET_PSDU_LEN0_SHIFT                                       (5)
#define RESET_REPCODE0_MASK                                         (0x00000010)
#define RESET_REPCODE0_SHIFT                                        (4)
#define RESET_PAYLOAD_CRC_FAIL_MASK                                 (0x00000008)
#define RESET_PAYLOAD_CRC_FAIL_SHIFT                                (3)
#define RESET_PAYLOAD_CRC_PASS_MASK                                 (0x00000004)
#define RESET_PAYLOAD_CRC_PASS_SHIFT                                (2)
#define RESET_HEADER_CRC_FAIL_MASK                                  (0x00000002)
#define RESET_HEADER_CRC_FAIL_SHIFT                                 (1)
#define RESET_HEADER_CRC_PASS_MASK                                  (0x00000001)
#define RESET_HEADER_CRC_PASS_SHIFT                                 (0)
#define NEXT_MEMBANK_TO_READ_MASK                                   (0x00000003)
#define NEXT_MEMBANK_TO_READ_SHIFT                                  (0)
#define RX_PSDU_LENGTH_MASK                                         (0x03FF0000)
#define RX_PSDU_LENGTH_SHIFT                                        (16)
#define RX_REP_CODE_MASK                                            (0x000000FF)
#define RX_REP_CODE_SHIFT                                           (0)
#define RX_PREAMBLE_MASK                                            (0x00070000)
#define RX_PREAMBLE_SHIFT                                           (16)
#define XCORR_THRESH_MASK                                           (0x0000FFFF)
#define XCORR_THRESH_SHIFT                                          (0)
#define PROC_FIFO_WR_LEVEL_MASK                                     (0x0000F000)
#define PROC_FIFO_WR_LEVEL_SHIFT                                    (12)
#define PROC_FIFO_RD_LEVEL_MASK                                     (0x00000F00)
#define PROC_FIFO_RD_LEVEL_SHIFT                                    (8)
#define NEXTBUF_FIFO_WR_LEVEL_MASK                                  (0x000000F0)
#define NEXTBUF_FIFO_WR_LEVEL_SHIFT                                 (4)
#define NEXTBUF_FIFO_RD_LEVEL_MASK                                  (0x0000000F)
#define NEXTBUF_FIFO_RD_LEVEL_SHIFT                                 (0)
#define CCA_AUTO_CORR_MASK                                          (0x80000000)
#define CCA_AUTO_CORR_SHIFT                                         (31)
#define ED_CHAN_BUSY_MASK                                           (0x40000000)
#define ED_CHAN_BUSY_SHIFT                                          (30)
#define HP_AUTO_CORR_MASK                                           (0x20000000)
#define HP_AUTO_CORR_SHIFT                                          (29)
#define RX_RSSI_LATCHED_MASK                                        (0x00FF0000)
#define RX_RSSI_LATCHED_SHIFT                                       (16)
#define RX_PGA_FREE_MASK                                            (0x00003F00)
#define RX_PGA_FREE_SHIFT                                           (8)
#define RX_PGA_LATCHED_MASK                                         (0x0000003F)
#define RX_PGA_LATCHED_SHIFT                                        (0)
#define RX_FIFO_EMPTY_MASK                                          (0x00400000)
#define RX_FIFO_EMPTY_SHIFT                                         (22)
#define RX_FIFO_FULL_MASK                                           (0x00200000)
#define RX_FIFO_FULL_SHIFT                                          (21)
#define RX_MEMBANK_OFLOW_MASK                                       (0x00100000)
#define RX_MEMBANK_OFLOW_SHIFT                                      (20)
#define MEMBANK3_FULL_MASK                                          (0x00080000)
#define MEMBANK3_FULL_SHIFT                                         (19)
#define MEMBANK2_FULL_MASK                                          (0x00040000)
#define MEMBANK2_FULL_SHIFT                                         (18)
#define MEMBANK1_FULL_MASK                                          (0x00020000)
#define MEMBANK1_FULL_SHIFT                                         (17)
#define MEMBANK0_FULL_MASK                                          (0x00010000)
#define MEMBANK0_FULL_SHIFT                                         (16)
#define RX_RSSI_FREE_MASK                                           (0x000000FF)
#define RX_RSSI_FREE_SHIFT                                          (0)

/* ___________________ Medium Access Controller
 */
#define TRAFMON_ENABLE_MASK                                         (0x00000001)
#define TRAFMON_ENABLE_SHIFT                                        (0)
#define TRAFMON_CLEAR_MASK                                          (0x00000001)
#define TRAFMON_CLEAR_SHIFT                                         (0)
#define MAC_LIFS_PERIOD_MASK                                        (0x3F000000)
#define MAC_LIFS_PERIOD_SHIFT                                       (24)
#define MAC_SIFS_PERIOD_MASK                                        (0x003F0000)
#define MAC_SIFS_PERIOD_SHIFT                                       (16)
#define MAC_MAX_SIFS_FRAME_SIZE_MASK                                (0x00001F00)
#define MAC_MAX_SIFS_FRAME_SIZE_SHIFT                               (8)
#define MAC_IFS_ENABLE_MASK                                         (0x00000001)
#define MAC_IFS_ENABLE_SHIFT                                        (0)
#define TRAFMON_PSDULEN_AVG_MASK                                    (0x0000007F)
#define TRAFMON_PSDULEN_AVG_SHIFT                                   (0)
#define TRAFMON_REPCODE_AVG_MASK                                    (0x000000FF)
#define TRAFMON_REPCODE_AVG_SHIFT                                   (0)
#define TRAFMON_HDR_CRC_PASS_MASK                                   (0x00003FFF)
#define TRAFMON_HDR_CRC_PASS_SHIFT                                  (0)
#define TRAFMON_HDR_CRC_FAIL_MASK                                   (0x00003FFF)
#define TRAFMON_HDR_CRC_FAIL_SHIFT                                  (0)
#define TRAFMON_PAY_CRC_FAIL_MASK                                   (0x00003FFF)
#define TRAFMON_PAY_CRC_FAIL_SHIFT                                  (0)
#define TRAFMON_CCA_MASK                                            (0x00003FFF)
#define TRAFMON_CCA_SHIFT                                           (0)
#define TRAFMON_PKT_TIME_MASK                                       (0x00003FFF)
#define TRAFMON_PKT_TIME_SHIFT                                      (0)
#define TRAFMON_HP_MASK                                             (0x00003FFF)
#define TRAFMON_HP_SHIFT                                            (0)
#define MAC_EA_LOWER_MASK                                           (0xFFFFFFFF)
#define MAC_EA_LOWER_SHIFT                                          (0)
#define MAC_EA_UPPER_MASK                                           (0xFFFFFFFF)
#define MAC_EA_UPPER_SHIFT                                          (0)
#define MAC_SA_MASK                                                 (0x0000FFFF)
#define MAC_SA_SHIFT                                                (0)
#define MAC_PAN_ID_MASK                                             (0x0000FFFF)
#define MAC_PAN_ID_SHIFT                                            (0)
#define MAC_CTRL_IGN_FCS_PAYLOAD_MASK                               (0x00000008)
#define MAC_CTRL_IGN_FCS_PAYLOAD_SHIFT                              (3)
#define MAC_CTRL_IGN_FCS_HEADER_MASK                                (0x00000004)
#define MAC_CTRL_IGN_FCS_HEADER_SHIFT                               (2)
#define MAC_CTRL_PAN_COORD_MASK                                     (0x00000002)
#define MAC_CTRL_PAN_COORD_SHIFT                                    (1)
#define MAC_CTRL_FILTER_EN_MASK                                     (0x00000001)
#define MAC_CTRL_FILTER_EN_SHIFT                                    (0)
#define MAC_TIMEOUT_STRATEGY_MASK                                   (0x00060000)
#define MAC_TIMEOUT_STRATEGY_SHIFT                                  (17)
#define MAC_MAX_CSMA_BACKOFFS_MASK                                  (0x0001F000)
#define MAC_MAX_CSMA_BACKOFFS_SHIFT                                 (12)
#define MAC_MIN_BE_MASK                                             (0x00000F00)
#define MAC_MIN_BE_SHIFT                                            (8)
#define MAC_MAX_BE_MASK                                             (0x000000F0)
#define MAC_MAX_BE_SHIFT                                            (4)
#define MAC_CSMA_IGN_RX_BUSY_FOR_TX_MASK                            (0x00000008)
#define MAC_CSMA_IGN_RX_BUSY_FOR_TX_SHIFT                           (3)
#define LOWER_MAC_ACK_OVERRIDE_MASK                                 (0x00000004)
#define LOWER_MAC_ACK_OVERRIDE_SHIFT                                (2)
#define LOWER_MAC_RESET_MASK                                        (0x00000002)
#define LOWER_MAC_RESET_SHIFT                                       (1)
#define MAC_BYPASS_MASK                                             (0x00000001)
#define MAC_BYPASS_SHIFT                                            (0)
#define MAC_LOWER_TX_TIMOUT_OCCURRED_MASK                           (0x00010000)
#define MAC_LOWER_TX_TIMOUT_OCCURRED_SHIFT                          (16)
#define MAC_LOWER_BACKOFF_ATTEMPTS_MASK                             (0x00001F00)
#define MAC_LOWER_BACKOFF_ATTEMPTS_SHIFT                            (8)
#define MAC_LOWER_STATE_MASK                                        (0x0000000F)
#define MAC_LOWER_STATE_SHIFT                                       (0)
#define MAC_ACK_PGA_GAIN_MASK                                       (0x00FF0000)
#define MAC_ACK_PGA_GAIN_SHIFT                                      (16)
#define MAC_ACK_REP_CODE_MASK                                       (0x0000FF00)
#define MAC_ACK_REP_CODE_SHIFT                                      (8)
#define MAC_ACK_SEQ_CHECK_ENABLE_MASK                               (0x00000004)
#define MAC_ACK_SEQ_CHECK_ENABLE_SHIFT                              (2)
#define MAC_ACK_DESTINATION_MASK                                    (0x00000002)
#define MAC_ACK_DESTINATION_SHIFT                                   (1)
#define MAC_ACK_ENABLE_MASK                                         (0x00000001)
#define MAC_ACK_ENABLE_SHIFT                                        (0)
#define MAC_ACK_EXTRA_HDR_MASK                                      (0xFFFF0000)
#define MAC_ACK_EXTRA_HDR_SHIFT                                     (16)
#define MAC_ACK_FC1_MASK                                            (0x0000FF00)
#define MAC_ACK_FC1_SHIFT                                           (8)
#define MAC_ACK_FC0_MASK                                            (0x000000FF)
#define MAC_ACK_FC0_SHIFT                                           (0)
#define MAC_MAX_RETRIES_MASK                                        (0x001F0000)
#define MAC_MAX_RETRIES_SHIFT                                       (16)
#define MAC_ACK_WAIT_DURATION_MASK                                  (0x00000FFF)
#define MAC_ACK_WAIT_DURATION_SHIFT                                 (0)
#define MAC_ACK_SUCCESS_MASK                                        (0x00000020)
#define MAC_ACK_SUCCESS_SHIFT                                       (5)
#define MAC_RETRY_ATTEMPTS_MASK                                     (0x0000001F)
#define MAC_RETRY_ATTEMPTS_SHIFT                                    (0)
#define MAC_ACK_SEQ_NUM_MASK                                        (0x00FF0000)
#define MAC_ACK_SEQ_NUM_SHIFT                                       (16)
#define MAC_ACK_FC_MASK                                             (0x0000FFFF)
#define MAC_ACK_FC_SHIFT                                            (0)

/* ___________________ Power Up Controller
 */
#define PUP_KICK_OFF_SPI_WRITE_MASK                                 (0x00000001)
#define PUP_KICK_OFF_SPI_WRITE_SHIFT                                (0)
#define PUP_KICK_OFF_SPI_READ_MASK                                  (0x00000001)
#define PUP_KICK_OFF_SPI_READ_SHIFT                                 (0)
#define PUP_PGA_MUX_SELECT_MASK                                     (0x00000001)
#define PUP_PGA_MUX_SELECT_SHIFT                                    (0)
#define PUP_TX_TONEGEN_MUX_SELECT_MASK                              (0x00000001)
#define PUP_TX_TONEGEN_MUX_SELECT_SHIFT                             (0)
#define RELAY_MASK                                                  (0x00000001)
#define RELAY_SHIFT                                                 (0)
#define FPGA_CONFIG_MASK                                            (0x00000001)
#define FPGA_CONFIG_SHIFT                                           (0)

/* ___________________ AFE Controller
 */
#define AFE_AD9865_SINGLE_REG_WR_DATA_MASK                          (0xFF000000)
#define AFE_AD9865_SINGLE_REG_WR_DATA_SHIFT                         (24)
#define AFE_SINGLE_AD9865_ADDR_MASK                                 (0x001F0000)
#define AFE_SINGLE_AD9865_ADDR_SHIFT                                (16)
#define AFE_AGC_FIXED_GAIN_MASK                                     (0x00003F00)
#define AFE_AGC_FIXED_GAIN_SHIFT                                    (8)
#define AFE_SINGLE_AD9865_ACCESS_MASK                               (0x00000001)
#define AFE_SINGLE_AD9865_ACCESS_SHIFT                              (0)
#define SPI_READ_DONE_MASK                                          (0x00000004)
#define SPI_READ_DONE_SHIFT                                         (2)
#define SPI_WRITE_DONE_MASK                                         (0x00000002)
#define SPI_WRITE_DONE_SHIFT                                        (1)
#define SW_RESET_DONE_MASK                                          (0x00000001)
#define SW_RESET_DONE_SHIFT                                         (0)

/* ___________________ Hardware Version Control
 */


/* _____________________________________________________________________ Offsets
 */

/* ___________________ Transceiver
 */
#define TX_CONTROL                                                 (0)
#define TX_PARAMS_BANK0                                            (1)
#define TX_EXTRA_HDR_BANK0                                         (2)
#define TX_PARAMS_BANK1                                            (3)
#define TX_EXTRA_HDR_BANK1                                         (4)
#define RX_CONTROL                                                 (5)
#define RX_HDR_REP_RATE                                            (7)
#define RX_THRESHOLDS                                              (8)
#define RX_RESETS                                                  (9)
#define RX_NEXT_MEM_BANK_TO_READ                                   (10)
#define RX_HDR_CRC_PASS                                            (11)
#define RX_HDR_CRC_FAIL                                            (12)
#define RX_PAY_CRC_PASS                                            (13)
#define RX_PAY_CRC_FAIL                                            (14)
#define RX_RC_PSDU_BANK0                                           (15)
#define RX_HDR_XTRA_BANK0                                          (16)
#define RX_CRCS_BANK0                                              (17)
#define RX_RC_PSDU_BANK1                                           (18)
#define RX_HDR_XTRA_BANK1                                          (19)
#define RX_CRCS_BANK1                                              (20)
#define RX_RC_PSDU_BANK2                                           (21)
#define RX_HDR_XTRA_BANK2                                          (22)
#define RX_CRCS_BANK2                                              (23)
#define RX_RC_PSDU_BANK3                                           (24)
#define RX_HDR_XTRA_BANK3                                          (25)
#define RX_CRCS_BANK3                                              (26)
#define RX_XCORR_THRESH                                            (27)
#define RX_FIFO_LEVELS                                             (28)
#define TRX_HARD_RESET                                             (29)
#define RX_PGA_CCA_FLAGS                                           (30)
#define RX_RSSI_MEM_FLAGS_TXPWR                                    (31)

/* ___________________ Medium Access Controller
 */
#define MAC_TRAFMON_CTRL                                           (0)
#define MAC_TRAFMON_CLEAR                                          (1)
#define MAC_IFS                                                    (2)
#define MAC_TRAFMON_PSDULEN_AVG                                    (10)
#define MAC_TRAFMON_REPCODE_AVG                                    (11)
#define MAC_TRAFMON_HDR_CRC_PASS                                   (12)
#define MAC_TRAFMON_HDR_CRC_FAIL                                   (13)
#define MAC_TRAFMON_PAY_CRC_FAIL                                   (14)
#define MAC_TRAFMON_CCA                                            (15)
#define MAC_TRAFMON_PKT_TIME                                       (16)
#define MAC_TRAFMON_HP                                             (17)
#define MAC_FILTER_EA_LOWER                                        (18)
#define MAC_FILTER_EA_UPPER                                        (19)
#define MAC_FILTER_SA                                              (20)
#define MAC_FILTER_PAN_ID                                          (21)
#define MAC_FILTER_CTRL                                            (22)
#define MAC_LOWER_CTRL                                             (23)
#define MAC_LOWER_STATUS                                           (24)
#define MAC_ACK_CTRL                                               (25)
#define MAC_ACK_PAYLOAD                                            (26)
#define MAC_ACK_PROC_CTRL                                          (27)
#define MAC_ACK_PROC_STATUS                                        (28)
#define MAC_ACK_DATA                                               (29)

/* ___________________ Power Up Controller
 */
#define PWR_SPI_WRITE                                              (1)
#define PWR_SPI_READ                                               (2)
#define PWR_TRX_SELECT                                             (3)
#define PWR_PGA_MUX_SEL                                            (4)
#define PWR_TONGEN_SEL                                             (5)
#define PWR_RELAY                                                  (9)
#define PWR_FPGA_CONFIG                                            (10)
#define PWR_DIPS_BOARD                                             (18)
#define PWR_DIPS_MODEM                                             (19)

/* ___________________ AFE Controller
 */
#define AFE_AGC_FIXED_GAIN                                         (0)
#define AFE_STATUS                                                 (1)

/* ___________________ Hardware Version Control
 */
#define HWVERS_MAJOR                                               (0)
#define HWVERS_MINOR                                               (1)
#define HWVERS_REVISION                                            (2)
#define HWVERS_PROC_INTERFACE                                      (3)
#define HWVERS_DB                                                  (4)


#endif

