/*
 * Register Access Implementatio for QEMU Hanadu Virtual Device.
 * Processor Interface Version: 1
 * 
 * THIS FILE IS AUTOMATICALLY GENERATED USING THE REGISTER MAP PROJECT.
 * PLEASE DO NOT EDIT.
 *
 * Martin Townsend >martin.townsend@xsilon.com<
 * Copyright Xsilon Limited 2014.
 */

#include "hanadu.h"



/* ___________________ Transceiver
 */

uint64_t
han_trxm_mem_region_read(void *opaque, hwaddr addr, unsigned size)
{
    struct han_trxm_dev *s = HANADU_TRXM_DEV(opaque);
    uint32_t * regs = (uint32_t *)&s->regs;

    addr >>= 2;
    assert(addr < 32);
    return regs[addr];
}

void
han_trxm_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size)
{
}


/* ___________________ Medium Access Controller
 */

uint64_t
han_mac_mem_region_read(void *opaque, hwaddr addr, unsigned size)
{
    struct han_mac_dev *s = HANADU_MAC_DEV(opaque);
    uint32_t * regs = (uint32_t *)&s->regs;

    addr >>= 2;
    assert(addr < 32);
    return regs[addr];
}

void
han_mac_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size)
{
}


/* ___________________ Power Up Controller
 */

uint64_t
han_pwr_mem_region_read(void *opaque, hwaddr addr, unsigned size)
{
    struct han_pwr_dev *s = HANADU_PWR_DEV(opaque);
    uint32_t * regs = (uint32_t *)&s->regs;

    addr >>= 2;
    assert(addr < 32);
    return regs[addr];
}

void
han_pwr_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size)
{
}


/* ___________________ AFE Controller
 */
 
uint64_t
han_afe_mem_region_read(void *opaque, hwaddr addr, unsigned size)
{
    struct han_afe_dev *s = HANADU_AFE_DEV(opaque);
    uint32_t * regs = (uint32_t *)&s->regs;

    addr >>= 2;
    assert(addr < 32);
    return regs[addr];
}

void
han_afe_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size)
{
}


/* ___________________ Hardware Version Control
 */

uint64_t
han_hwvers_mem_region_read(void *opaque, hwaddr addr, unsigned size)
{
    struct han_hwvers_dev *s = HANADU_HWVERS_DEV(opaque);
    uint32_t * regs = (uint32_t *)&s->regs;

    addr >>= 2;
    assert(addr < 32);
    return regs[addr];
}

void
han_hwvers_mem_region_write(void *opaque, hwaddr addr, uint64_t value, unsigned size)
{
}

